name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        touch src/api.rs
        echo 'pub const APIKEY: &str = "${{ secrets.COHEREKEY }}";' >> src/api.rs
        cat src/api.rs
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx use honeydew-rs-builder
        docker buildx build --file Dockerfile --tag conradmo/honeydew-rs-image --push .
      shell: bash
