name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        touch src/api.rs
        echo 'pub const APIKEY: &str = "${{ secrets.COHEREKEY }}";' >> src/api.rs
        cat src/api.rs
    - name: Set up Docker Buildx
      run: |
          docker build --build-arg BUILDKIT_INLINE_CACHE=1 -t conradmo/honeydew-rs-image .
          docker run --rm --privileged tonistiigi/binfmt --install all
          docker buildx create --use --name honeydew-rs-builder --driver-opt network=host --buildkitd-flags '--allow-insecure-entitlement security.insecure' --use
          docker buildx inspect honeydew-rs-builder --bootstrap
      shell: bash
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker buildx use honeydew-rs-builder
        docker buildx build --file Dockerfile --tag conradmo/honeydew-rs-image --push .
      shell: bash
    - name: Create SSH key
      run: |
        echo "$SSH_KEY" > key.pem
        sudo chmod 400 key.pem
      shell: bash
      env:
        SSH_KEY: ${{secrets.SSHKEY}}
    - name: Ssh into AWS EC2
      run: |
        ssh -i "key.pem" ubuntu@ec2-18-219-119-135.us-east-2.compute.amazonaws.com
    - name: Update docker image
      run: |
        sudo docker stop $(sudo docker ps -a -q)
        sudo docker rm $(sudo docker ps -a -q)
        sudo docker pull conradmo/honeydew-rs-image
        sudo docker run -d -p 3000:3000 conradmo/honeydew-rs-image
