name: Rust

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: |
        touch src/api.rs
        echo -e "${{ secrets.COHEREKEY }}" >> src/api.rs
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
